name: Auto PR to Develop

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "Auto PR: Merge into develop"
